<?php
    $_list = $this->getChild('alsoviewed.list');
    if (!$_list) :
        return;
    endif;

    $_productCollection = $_list->getProductCollection();
    if (!$_productCollection->getSize()) :
        return;
    endif;
?>

<div class="block alsoviewed">
    <div class="block-title"><strong><span><?php echo $this->__("You may also like"); ?></span></strong></div>
    <div class="block-content">
        <?php echo $this->getChildHtml('alsoviewed.list') ?>
    </div>
</div>
