<?php
    $_list = $this->getChild('alsoviewed.list');
    if (!$_list) :
        return;
    endif;

    $_productCollection = $_list->getProductCollection();
    if (!$_productCollection->getSize()) :
        return;
    endif;

    $_title = $this->getTitle();
    if (null === $_title) :
        $_title = $_list->getTitle();
    endif;
?>

<div class="block alsoviewed">
    <div class="block-title"><strong><span><?php echo $this->__($_title); ?></span></strong></div>
    <div class="block-content">
        <?php echo $this->getChildHtml('alsoviewed.list') ?>
    </div>
</div>
